In [1]:
import numpy as np

class ChromaticWorld():

    def __init__(self):
        self.chromatic_scale_numeric = np.arange(0, 12, dtype = np.uint8)

        # using Mixed In Key's enharmonic spellings
        self.array_chromatic_scale_pitch_classes = np.array(
            [
                'C', 'Db', 'D', 'Eb', 'E', 'F',
                'F#', 'G', 'Ab', 'A', 'Bb', 'B',
            ],
            dtype = str
        )
        
        self.compute_circle_of_fifths()
        self.compute_minor_offset()
    
    def compute_circle_of_fifths(self):
        circle_of_fifths = [0]
        for pitch_class in self.chromatic_scale_numeric[1:]:
            circle_of_fifths.append((circle_of_fifths[-1] + 7) % 12)
        self.circle_of_fifths_numeric = np.array(circle_of_fifths, dtype = np.uint8)

    def compute_minor_offset(self):
        minor_offset_fifths = []
        for pitch_class in self.circle_of_fifths_numeric:
            minor_offset_fifths.append((pitch_class + 9) % 12)
        self.minor_offset_fifths_numeric = np.array(minor_offset_fifths, dtype = np.uint8)



In [2]:
c = ChromaticWorld()
print(c.chromatic_scale_numeric)
print(c.circle_of_fifths_numeric)
print(c.minor_offset_fifths_numeric)
print(len(c.array_chromatic_scale_pitch_classes))
print(c.array_chromatic_scale_pitch_classes)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  7  2  9  4 11  6  1  8  3 10  5]
[ 9  4 11  6  1  8  3 10  5  0  7  2]
12
['C' 'Db' 'D' 'Eb' 'E' 'F' 'F#' 'G' 'Ab' 'A' 'Bb' 'B']


In [3]:
c.array_chromatic_scale_pitch_classes[c.circle_of_fifths_numeric]

array(['C', 'G', 'D', 'A', 'E', 'B', 'F#', 'Db', 'Ab', 'Eb', 'Bb', 'F'],
      dtype='<U2')

In [4]:
camelot_major = np.array([str(((q + 7) % 12) + 1) + 'B' for q in range(0, 12)], dtype = str)
camelot_minor = np.array([str(((q + 7) % 12) + 1) + 'A' for q in range(0, 12)], dtype = str)

In [17]:
camelot_wheel_B_layer = list(
    zip(
        c.array_chromatic_scale_pitch_classes[c.circle_of_fifths_numeric],
        camelot_major
    )
)

In [18]:
camelot_wheel_A_layer = list(
    zip(
        c.array_chromatic_scale_pitch_classes[c.minor_offset_fifths_numeric],
        camelot_minor
    )
)

In [20]:
list(zip(camelot_wheel_A_layer, camelot_wheel_B_layer))

[(('A', '8A'), ('C', '8B')),
 (('E', '9A'), ('G', '9B')),
 (('B', '10A'), ('D', '10B')),
 (('F#', '11A'), ('A', '11B')),
 (('Db', '12A'), ('E', '12B')),
 (('Ab', '1A'), ('B', '1B')),
 (('Eb', '2A'), ('F#', '2B')),
 (('Bb', '3A'), ('Db', '3B')),
 (('F', '4A'), ('Ab', '4B')),
 (('C', '5A'), ('Eb', '5B')),
 (('G', '6A'), ('Bb', '6B')),
 (('D', '7A'), ('F', '7B'))]