In [3]:
import numpy as np

In [4]:
from music_production_and_performance.theory.western.scales.chromatic import chromatic_scale_pitch_class_names
from music_production_and_performance.theory.western.scales.chromatic import chromatic_scale_numeric

In [31]:
chromatic_scale_pitch_class_names = np.array(chromatic_scale_pitch_class_names)
chromatic_scale_numeric = np.array(chromatic_scale_numeric)

print(chromatic_scale_pitch_class_names)
print(chromatic_scale_numeric)

['C' 'Db' 'D' 'Eb' 'E' 'F' 'F#' 'G' 'Ab' 'A' 'Bb' 'B']
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [60]:
#diatonic_mode_names = ['Ionian', 'Dorian', 'Phrygian', 'Lydian', 'Mixolydian', 'Aeolian', 'Locrian']
#Ionian_mode = ['C', 'D', 'E', 'F', 'G', 'A', 'B']

def roll_the_modes(
    diatonic_mode_names = ['Ionian', 'Dorian', 'Phrygian', 'Lydian', 'Mixolydian', 'Aeolian', 'Locrian'],
    Ionian_mode = ['C', 'D', 'E', 'F', 'G', 'A', 'B'],
):
    name_list = []
    mode_list = []
    for i, name in zip(range(0, len(Ionian_mode)), diatonic_mode_names):
        mode = Ionian_mode[i:]
        mode.extend(Ionian_mode[0:i])
        #mode = np.array(mode)
        name_list.append(name)
        mode_list.append(mode)
        
    
    assert name_list == diatonic_mode_names
    return mode_list, name_list

mode_list, names_list = roll_the_modes()

#
# calculate the modes (C-based)
#
def calculate_the_modes(mode_list):
    all_modes_indices_list = []
    for mode in mode_list:
    
        # there is probably a more NumPy-ish way to do this with broadcasting...
        index_list = []
        for pitch_class in mode:
            index = list(chromatic_scale_pitch_class_names).index(pitch_class)
            index_list.append(index)

        all_modes_indices_list.append(np.array(index_list))
    all_modes_indices_list = np.array(all_modes_indices_list)

    X = np.zeros([len(all_modes_indices_list[:, 0]), 1])
    X[:, 0] = all_modes_indices_list[:, 0]
    q = all_modes_indices_list - X
    r = q % 12
    r = np.int8(r)
    return r

import pprint as pp
pp.pprint(all_modes_indices_list)
print()
modes_numeric = calculate_the_modes(mode_list)
print(modes_numeric)

array([[ 0,  2,  4,  5,  7,  9, 11],
       [ 2,  4,  5,  7,  9, 11,  0],
       [ 4,  5,  7,  9, 11,  0,  2],
       [ 5,  7,  9, 11,  0,  2,  4],
       [ 7,  9, 11,  0,  2,  4,  5],
       [ 9, 11,  0,  2,  4,  5,  7],
       [11,  0,  2,  4,  5,  7,  9]])

[[ 0  2  4  5  7  9 11]
 [ 0  2  3  5  7  9 10]
 [ 0  1  3  5  7  8 10]
 [ 0  2  4  6  7  9 11]
 [ 0  2  4  5  7  9 10]
 [ 0  2  3  5  7  8 10]
 [ 0  1  3  5  6  8 10]]


In [77]:
# there is probably a better NumPy way to do this...

# Need to deal with the F and F# in the last mode

for mode_i in np.arange(0, modes_numeric.shape[0]):
    mode_index = modes_numeric[mode_i, :]
    cpcn = chromatic_scale_pitch_class_names[mode_index]

    print(np.unique(np.array([x[0] for x in cpcn]), return_counts = True))

(array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U1'), array([1, 1, 1, 1, 1, 1, 1]))
(array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U1'), array([1, 1, 1, 1, 1, 1, 1]))
(array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U1'), array([1, 1, 1, 1, 1, 1, 1]))
(array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U1'), array([1, 1, 1, 1, 1, 1, 1]))
(array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U1'), array([1, 1, 1, 1, 1, 1, 1]))
(array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U1'), array([1, 1, 1, 1, 1, 1, 1]))
(array(['A', 'B', 'C', 'D', 'E', 'F'], dtype='<U1'), array([1, 1, 1, 1, 1, 2]))
