## Import useful libraries

In [1]:
import numpy as np
import pprint as pp

In [2]:
from badass_music.theory.western.scales.chromatic import chromatic_scale_pitch_class_names
from badass_music.theory.western.scales.chromatic import chromatic_scale_numeric

## Switch to NumPy

In [3]:
chromatic_scale_pitch_class_names = np.array(chromatic_scale_pitch_class_names)
chromatic_scale_numeric = np.array(chromatic_scale_numeric)

print(chromatic_scale_pitch_class_names)
print(chromatic_scale_numeric)

['C' 'Db' 'D' 'Eb' 'E' 'F' 'F#' 'G' 'Ab' 'A' 'Bb' 'B']
[ 0  1  2  3  4  5  6  7  8  9 10 11]


## Define a function to convert Ionian mode to related modes

Default is to use C as the base pitch, which is generally how the assumed output will be used:

In [4]:
def roll_the_modes(
    diatonic_mode_names = ['Ionian', 'Dorian', 'Phrygian', 'Lydian', 'Mixolydian', 'Aeolian', 'Locrian'],
    Ionian_mode = ['C', 'D', 'E', 'F', 'G', 'A', 'B'],
):
    name_list = []
    mode_list = []
    for i, name in zip(range(0, len(Ionian_mode)), diatonic_mode_names):
        mode = Ionian_mode[i:]
        mode.extend(Ionian_mode[0:i])
        name_list.append(name)
        mode_list.append(mode)
        
    assert name_list == diatonic_mode_names
    return mode_list, name_list

In [5]:
mode_pitch_class_root_names_list, mode_names_list = roll_the_modes()

pp.pprint(mode_pitch_class_root_names_list)
print()
pp.pprint(mode_names_list)

[['C', 'D', 'E', 'F', 'G', 'A', 'B'],
 ['D', 'E', 'F', 'G', 'A', 'B', 'C'],
 ['E', 'F', 'G', 'A', 'B', 'C', 'D'],
 ['F', 'G', 'A', 'B', 'C', 'D', 'E'],
 ['G', 'A', 'B', 'C', 'D', 'E', 'F'],
 ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
 ['B', 'C', 'D', 'E', 'F', 'G', 'A']]

['Ionian', 'Dorian', 'Phrygian', 'Lydian', 'Mixolydian', 'Aeolian', 'Locrian']


In [6]:
#
# calculate the modes (C-based)
#
def calculate_the_modes(mode_list):
    all_modes_indices_list = []
    for mode in mode_list:
    
        # there is probably a more NumPy-ish way to do this with broadcasting...
        index_list = []
        for pitch_class in mode:
            index = list(chromatic_scale_pitch_class_names).index(pitch_class)
            index_list.append(index)

        all_modes_indices_list.append(np.array(index_list))
    all_modes_indices_list = np.array(all_modes_indices_list)

    X = np.zeros([len(all_modes_indices_list[:, 0]), 1])
    X[:, 0] = all_modes_indices_list[:, 0]
    q = all_modes_indices_list - X
    r = q % 12
    r = np.int8(r)
    return r

modes_numeric = calculate_the_modes(mode_pitch_class_root_names_list)
print(modes_numeric)

[[ 0  2  4  5  7  9 11]
 [ 0  2  3  5  7  9 10]
 [ 0  1  3  5  7  8 10]
 [ 0  2  4  6  7  9 11]
 [ 0  2  4  5  7  9 10]
 [ 0  2  3  5  7  8 10]
 [ 0  1  3  5  6  8 10]]


In [7]:
# there is probably a better NumPy way to do this...

# Need to deal with the F and F# in the last mode

for mode_i in np.arange(0, modes_numeric.shape[0]):
    mode_index = modes_numeric[mode_i, :]
    cpcn = chromatic_scale_pitch_class_names[mode_index]

    print(np.unique(np.array([x[0] for x in cpcn]), return_counts = True))

(array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U1'), array([1, 1, 1, 1, 1, 1, 1]))
(array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U1'), array([1, 1, 1, 1, 1, 1, 1]))
(array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U1'), array([1, 1, 1, 1, 1, 1, 1]))
(array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U1'), array([1, 1, 1, 1, 1, 1, 1]))
(array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U1'), array([1, 1, 1, 1, 1, 1, 1]))
(array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U1'), array([1, 1, 1, 1, 1, 1, 1]))
(array(['A', 'B', 'C', 'D', 'E', 'F'], dtype='<U1'), array([1, 1, 1, 1, 1, 2]))


In [9]:
from badass_music.theory.western.transposition import chromatic_transpose

x = chromatic_transpose(chromatic_scale_numeric, verbose = True)
x = chromatic_transpose(chromatic_scale_numeric, chromatic_interval = -7, verbose = True)
x = chromatic_transpose(chromatic_scale_numeric, chromatic_interval = 60, verbose = True)
x = chromatic_transpose(chromatic_scale_numeric, chromatic_interval = 120, verbose = True)
x = chromatic_transpose(chromatic_scale_numeric, chromatic_interval = 127, verbose = True)
x = chromatic_transpose(chromatic_scale_numeric, chromatic_interval = 132, verbose = True)


Sequence provided by user: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Chromatic interval provided by user: 7
Transposed pitch numbers: [ 7  8  9 10 11 12 13 14 15 16 17 18]
Corresponding octaves: [-1 -1 -1 -1 -1  0  0  0  0  0  0  0]

Sequence provided by user: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Chromatic interval provided by user: -7
Transposed pitch numbers: [-7 -6 -5 -4 -3 -2 -1  0  1  2  3  4]
Corresponding octaves: [-2 -2 -2 -2 -2 -2 -2 -1 -1 -1 -1 -1]

Sequence provided by user: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Chromatic interval provided by user: 60
Transposed pitch numbers: [60 61 62 63 64 65 66 67 68 69 70 71]
Corresponding octaves: [4 4 4 4 4 4 4 4 4 4 4 4]

Sequence provided by user: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Chromatic interval provided by user: 120
Transposed pitch numbers: [120 121 122 123 124 125 126 127 128 129 130 131]
Corresponding octaves: [9 9 9 9 9 9 9 9 9 9 9 9]

Sequence provided by user: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Chromatic interval prov